logging:
  config: classpath:logback-test.xml
spring:
  datasource:
    url: jdbc:h2:mem:pacyorky
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
game:
  secondsBeforeStart: 120
  secondsBeforeStep: 120
  maxAttemptsForStep: 10
  maxAttemptsForStart: 10
  maxGames: 10
