server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${GAME_USER:toor}
    password: ${GAME_PASS:tooor}
    url: ${DB_GAME_HOST:jdbc:mysql://localhost:3306/pacyorky-game?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
    servlet:
      path: /api
game:
  secondsBeforeStart: 120
  secondsBeforeStep: 120
  maxAttemptsForStep: 10
  maxAttemptsForStart: 10
  maxGames: 10
  secretKey: ${GAME_SECRET:secret}
telegram:
  token: ${TELEGRAM_TOKEN}
  chat: ${TELEGRAM_CHAT}
logging:
  config: classpath:logback-spring.xml
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always







