server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${GAME_USER:root}
    password: ${GAME_PASS:toor}
    url: ${DB_GAME_HOST:jdbc:mysql://localhost:3306/pacyorky-game?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
    hikari:
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  flyway:
    enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
    servlet:
      path: /api
game:
  secondsBeforeStart: 120
  secondsBeforeStep: 60
  maxAttemptsForStep: 5
  maxAttemptsForStart: 10
  maxGames: 10
  secretKey: ${GAME_SECRET:secret}
agora:
  agoraId: ${AGORA_ID:id}
  agoraCertificate: ${AGORA_CERT:cert}
  createTokenOnCreateGame: false
telegram:
  token: ${TELEGRAM_TOKEN}
  chat: ${TELEGRAM_CHAT}
logging:
  config: classpath:logback-spring.xml
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always







