logging:
  config: classpath:logback-test.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${GAME_USER:root}
    password: ${GAME_PASS:toor}
    url: ${DB_GAME_HOST:jdbc:mysql://localhost:3306/pacyorky-game-test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    enabled: false
game:
  secondsBeforeStart: 120
  secondsBeforeStep: 120
  maxAttemptsForStep: 10
  maxAttemptsForStart: 10
  maxGames: 10
  secretKey: ${GAME_SECRET:secret}
