INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (1, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (2, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (3, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (4, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (5, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (6, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (7, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (8, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (9, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (10, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (11, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (12, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (13, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (14, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (15, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (16, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (17, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (18, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (19, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (20, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (21, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (22, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (23, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (24, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (25, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (26, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (27, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (28, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (29, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (30, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (31, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (32, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (33, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (34, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (35, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (36, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (37, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (38, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (39, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (40, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (41, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (42, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (43, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (44, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (45, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (46, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (47, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (48, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (49, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (50, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (51, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (52, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (53, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (54, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (55, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (56, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (57, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (58, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (59, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (60, 1, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (61, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (62, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (63, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (64, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (65, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (66, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (67, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (68, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (69, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (70, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (71, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (72, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (73, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (74, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (75, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (76, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (77, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (78, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (79, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (80, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (81, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (82, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (83, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (84, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (85, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (86, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (87, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (88, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (89, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (90, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (91, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (92, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (93, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (94, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (95, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (96, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (97, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (98, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (99, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (100, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (101, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (102, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (103, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (104, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (105, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (106, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (107, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (108, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (109, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (110, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (111, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (112, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (113, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (114, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (115, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (116, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (117, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (118, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (119, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (120, 2, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (121, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (122, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (123, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (124, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (125, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (126, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (127, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (128, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (129, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (130, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (131, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (132, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (133, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (134, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (135, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (136, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (137, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (138, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (139, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (140, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (141, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (142, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (143, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (144, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (145, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (146, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (147, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (148, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (149, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (150, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (151, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (152, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (153, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (154, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (155, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (156, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (157, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (158, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (159, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (160, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (161, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (162, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (163, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (164, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (165, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (166, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (167, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (168, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (169, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (170, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (171, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (172, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (173, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (174, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (175, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (176, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (177, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (178, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (179, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (180, 3, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (181, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (182, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (183, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (184, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (185, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (186, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (187, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (188, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (189, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (190, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (191, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (192, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (193, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (194, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (195, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (196, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (197, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (198, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (199, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (200, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (201, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (202, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (203, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (204, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (205, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (206, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (207, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (208, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (209, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (210, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (211, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (212, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (213, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (214, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (215, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (216, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (217, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (218, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (219, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (220, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (221, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (222, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (223, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (224, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (225, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (226, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (227, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (228, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (229, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (230, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (231, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (232, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (233, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (234, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (235, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (236, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (237, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (238, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (239, 4, '');
INSERT INTO CARD (ID, CARD_TYPE, NAME)
VALUES (240, 4, '');