INSERT INTO CHARACTER (ID, NAME)
VALUES (1, '');
INSERT INTO CHARACTER (ID, NAME)
VALUES (2, '');
INSERT INTO CHARACTER (ID, NAME)
VALUES (3, '');
INSERT INTO CHARACTER (ID, NAME)
VALUES (4, '');
INSERT INTO CHARACTER (ID, NAME)
VALUES (5, '');
INSERT INTO CHARACTER (ID, NAME)
VALUES (6, '');