INSERT INTO CHARACTER (ID, NAME)
VALUES (1, 'dochka_solomia');
INSERT INTO CHARACTER (ID, NAME)
VALUES (2, 'dochka_orisja');
INSERT INTO CHARACTER (ID, NAME)
VALUES (3, 'gospodinja_ivga');
INSERT INTO CHARACTER (ID, NAME)
VALUES (4, 'baba_docka');
INSERT INTO CHARACTER (ID, NAME)
VALUES (5, 'gospodar_vukol');
INSERT INTO CHARACTER (ID, NAME)
VALUES (6, 'did_bojan');
INSERT INTO CHARACTER (ID, NAME)
VALUES (7, 'sin_gnat');
INSERT INTO CHARACTER (ID, NAME)
VALUES (8, 'legin_ustim');