INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (1, 123);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (1, 148);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (1, 149);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (1, 155);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (1, 160);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (1, 123);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (1, 205);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (2, 204);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (2, 131);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (2, 41);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (3, 158);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (3, 151);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (3, 53);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (4, 151);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (4, 81);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (5, 81);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (5, 146);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (6, 37);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (6, 149);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (6, 135);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (6, 160);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (7, 155);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (7, 37);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (7, 201);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (7, 204);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (7, 219);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (8, 91);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (8, 150);
INSERT INTO CHARACTER_UNLOVED_CARDS (CHARACTER_ID, UNLOVED_CARDS_ID)
VALUES (8, 133);