INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (1, 29);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (1, 46);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (2, 2);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (2, 3);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (3, 1);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (3, 33);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (4, 17);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (4, 32);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (4, 45);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (5, 18);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (5, 37);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (5, 6);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (6, 23);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (6, 4);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (7, 48);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (7, 4);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (8, 47);
INSERT INTO CHARACTER_FAVORITE_EVENT_DAYS (CHARACTER_ID, FAVORITE_EVENT_DAYS_ID)
VALUES (8, 9);