INSERT INTO CHARACTER_FAVORITE_EVENT_CARDS (CHARACTER_ID, FAVORITE_EVENT_CARDS_ID)
VALUES (1, 61);
INSERT INTO CHARACTER_FAVORITE_EVENT_CARDS (CHARACTER_ID, FAVORITE_EVENT_CARDS_ID)
VALUES (2, 101);
INSERT INTO CHARACTER_FAVORITE_EVENT_CARDS (CHARACTER_ID, FAVORITE_EVENT_CARDS_ID)
VALUES (3, 91);
INSERT INTO CHARACTER_FAVORITE_EVENT_CARDS (CHARACTER_ID, FAVORITE_EVENT_CARDS_ID)
VALUES (6, 62);
INSERT INTO CHARACTER_FAVORITE_EVENT_CARDS (CHARACTER_ID, FAVORITE_EVENT_CARDS_ID)
VALUES (7, 111);
INSERT INTO CHARACTER_FAVORITE_EVENT_CARDS (CHARACTER_ID, FAVORITE_EVENT_CARDS_ID)
VALUES (8, 81);