INSERT INTO HOLIDAY_CARD (ID, NAME, CARDS_IN_DECK)
VALUES (81, 'vechornici', 10);
INSERT INTO HOLIDAY_CARD (ID, NAME, CARDS_IN_DECK)
VALUES (91, 'yarmarok', 10);
INSERT INTO HOLIDAY_CARD (ID, NAME, CARDS_IN_DECK)
VALUES (101, 'yangel', 10);
INSERT INTO HOLIDAY_CARD (ID, NAME, CARDS_IN_DECK)
VALUES (61, 'vesillja', 1);
INSERT INTO HOLIDAY_CARD (ID, NAME, CARDS_IN_DECK)
VALUES (111, 'urodini', 10);
INSERT INTO HOLIDAY_CARD (ID, NAME, CARDS_IN_DECK)
VALUES (62, 'vhodini', 1);
INSERT INTO HOLIDAY_CARD (ID, NAME, CARDS_IN_DECK)
VALUES (63, 'buden', 18);