INSERT INTO CHARACTER_UNLOVED_HOLIDAYS_CARDS (CHARACTER_ID, UNLOVED_HOLIDAYS_CARDS_ID)
VALUES (4, 81);
INSERT INTO CHARACTER_UNLOVED_HOLIDAYS_CARDS (CHARACTER_ID, UNLOVED_HOLIDAYS_CARDS_ID)
VALUES (5, 81);
INSERT INTO CHARACTER_UNLOVED_HOLIDAYS_CARDS (CHARACTER_ID, UNLOVED_HOLIDAYS_CARDS_ID)
VALUES (8, 91);